# Generated by Django 5.2.10 on 2026-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
